### ISSUE TITLE
TypeError: keys must be a string

### ISSUE THREAD

**Issue by Almenon** [Almenon/AREPL-backend#104]
```python
	
Sorry, AREPL has ran into an error

Traceback (most recent call last):
  File "c:\Users\anon\.vscode\extensions\almenon.arepl-1.0.10\node_modules\arepl-backend\python\pythonEvaluator.py", line 422, in <module>
    myReturnInfo = exec_input(data.evalCode, data.savedCode, data.filePath)
  File "c:\Users\anon\.vscode\extensions\almenon.arepl-1.0.10\node_modules\arepl-backend\python\pythonEvaluator.py", line 390, in exec_input
    userVariables = pickle_user_vars(evalLocals)
  File "c:\Users\anon\.vscode\extensions\almenon.arepl-1.0.10\node_modules\arepl-backend\python\pythonEvaluator.py", line 274, in pickle_user_vars
    fail_safe=lambda x:"AREPL could not pickle this object"
  File "c:\Users\anon\.vscode\extensions\almenon.arepl-1.0.10\node_modules\arepl-backend\python\jsonpickle\pickler.py", line 80, in encode
    return backend.encode(context.flatten(value, reset=reset))
  File "c:\Users\anon\.vscode\extensions\almenon.arepl-1.0.10\node_modules\arepl-backend\python\jsonpickle\backend.py", line 165, in encode
    raise e
  File "c:\Users\anon\.vscode\extensions\almenon.arepl-1.0.10\node_modules\arepl-backend\python\jsonpickle\backend.py", line 162, in encode
    return self.backend_encode(name, obj)
  File "c:\Users\anon\.vscode\extensions\almenon.arepl-1.0.10\node_modules\arepl-backend\python\jsonpickle\backend.py", line 173, in backend_encode
    return self._encoders[name](*encoder_args, **encoder_kwargs)
  File "D:\Anaconda\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "D:\Anaconda\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\Anaconda\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
TypeError: keys must be a string
```

Not sure why this is happening. 

If anyone could provide the python code that causes this error that would be great.

**Comment by Almenon** [comment]
@mccannjb davvid fixed it :)

Your issue should be resolved in the next version of arepl. I'll let you know when it's released.
