### ISSUE TITLE
error when opening file descriptor directly

### ISSUE THREAD

**Issue by Almenon** [Almenon/AREPL-backend#125]
**Describe the bug**
In arepl v1.0.23 it runs into a error on the very first line:
```
hi
Traceback (most recent call last):
  File "c:\Users\almenon\.vscode\extensions\almenon.arepl-1.0.23\node_modules\arepl-backend\python\arepl_python_evaluator.py", line 275, in <module>
    main(input())
  File "c:\Users\almenon\.vscode\extensions\almenon.arepl-1.0.23\node_modules\arepl-backend\python\arepl_python_evaluator.py", line 266, in main
    print_output(return_info)
  File "c:\Users\almenon\.vscode\extensions\almenon.arepl-1.0.23\node_modules\arepl-backend\python\arepl_python_evaluator.py", line 239, in print_output
    print("6q3co7" + json.dumps(output, default=lambda x: x.__dict__))
OSError: [Errno 9] Bad file descriptor
```

In the beta version of arepl I'm testing it gets the following error:
```
Traceback (most recent call last):
  line 2, in <module>
OSError: [WinError 6] The handle is invalid
```

**To Reproduce**
```python
print('hi', file=open(1,'w'))
print('hi', file=open(1,'w'))
```

**Expected behavior**
The following print results are outputted:
```
hi
hi
```

**Screenshots**

**Other Information (please complete the following information):**
 - OS: Windows 10
 - Python Version: 3.8.1

**Additional context**
The workaround is using `sys.stdout` instead of `open(1,'w')`

**Comment by Almenon** [comment]
Related; https://github.com/Almenon/AREPL-vscode/issues/336

**Comment by Almenon** [comment]
Another error:
```python
print('hi', file=open(1,'w'))
print('hi')
```

```
Sorry, AREPL has ran into an error

Traceback (most recent call last):
  File "c:\dev\AREPL-vscode\node_modules\arepl-backend\python\arepl_python_evaluator.py", line 166, in exec_input
    exec(exec_args.evalCode, eval_locals)
  File "<string>", line 2, in <module>
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\dev\AREPL-vscode\node_modules\arepl-backend\python\arepl_python_evaluator.py", line 174, in exec_input
    raise UserError(exc_obj, exc_tb, eval_locals, execTime)
arepl_user_error.UserError: (OSError(9, 'Bad file descriptor'), <traceback object at 0x07A87208>, {'__doc__': None, '__file__': 'c:\\dev\\AREPL-vscode\\test\\manualAreplTests\\canLogStderr.py', '__loader__': <_frozen_importlib_external.SourceFileLoader object at 0x07A6A0E8>, '__name__': '__main__', '__package__': '', 'arepl_store': None, 'help': <function help_overload at 0x03001BB0>, 'input': <function input_overload at 0x03001C40>, 'howdoi': <function howdoi_wrapper at 0x03001DA8>, '__builtins__': {'__name__': 'builtins', '__doc__': "Built-in functions, exceptions, and other objects.\n\nNoteworthy: None is the `nil' object; Ellipsis represents `...' in slices.", '__package__': '', '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': ModuleSpec(name='builtins', loader=<class '_frozen_importlib.BuiltinImporter'>), '__build_class__': <built-in function __build_class__>, '__import__': <built-in function __import__>, 'abs': <built-in function abs>, 'all': <built-in function all>, 'any': <built-in function any>, 'ascii': <built-in function ascii>, 'bin': <built-in function bin>, 'breakpoint': <built-in function breakpoint>, 'callable': <built-in function callable>, 'chr': <built-in function chr>, 'compile': <built-in function compile>, 'delattr': <built-in function delattr>, 'dir': <built-in function dir>, 'divmod': <built-in function divmod>, 'eval': <built-in function eval>, 'exec': <built-in function exec>, 'format': <built-in function format>, 'getattr': <built-in function getattr>, 'globals': <built-in function globals>, 'hasattr': <built-in function hasattr>, 'hash': <built-in function hash>, 'hex': <built-in function hex>, 'id': <built-in function id>, 'input': <built-in function input>, 'isinstance': <built-in function isinstance>, 'issubclass': <built-in function issubclass>, 'iter': <built-in function iter>, 'len': <built-in function len>, 'locals': <built-in function locals>, 'max': <built-in function max>, 'min': <built-in function min>, 'next': <built-in function next>, 'oct': <built-in function oct>, 'ord': <built-in function ord>, 'pow': <built-in function pow>, 'print': <built-in function print>, 'repr': <built-in function repr>, 'round': <built-in function round>, 'setattr': <built-in function setattr>, 'sorted': <built-in function sorted>, 'sum': <built-in function sum>, 'vars': <built-in function vars>, 'None': None, 'Ellipsis': Ellipsis, 'NotImplemented': NotImplemented, 'False': False, 'True': True, 'bool': <class 'bool'>, 'memoryview': <class 'memoryview'>, 'bytearray': <class 'bytearray'>, 'bytes': <class 'bytes'>, 'classmethod': <class 'classmethod'>, 'complex': <class 'complex'>, 'dict': <class 'dict'>, 'enumerate': <class 'enumerate'>, 'filter': <class 'filter'>, 'float': <class 'float'>, 'frozenset': <class 'frozenset'>, 'property': <class 'property'>, 'int': <class 'int'>, 'list': <class 'list'>, 'map': <class 'map'>, 'object': <class 'object'>, 'range': <class 'range'>, 'reversed': <class 'reversed'>, 'set': <class 'set'>, 'slice': <class 'slice'>, 'staticmethod': <class 'staticmethod'>, 'str': <class 'str'>, 'super': <class 'super'>, 'tuple': <class 'tuple'>, 'type': <class 'type'>, 'zip': <class 'zip'>, '__debug__': True, 'BaseException': <class 'BaseException'>, 'Exception': <class 'Exception'>, 'TypeError': <class 'TypeError'>, 'StopAsyncIteration': <class 'StopAsyncIteration'>, 'StopIteration': <class 'StopIteration'>, 'GeneratorExit': <class 'GeneratorExit'>, 'SystemExit': <class 'SystemExit'>, 'KeyboardInterrupt': <class 'KeyboardInterrupt'>, 'ImportError': <class 'ImportError'>, 'ModuleNotFoundError': <class 'ModuleNotFoundError'>, 'OSError': <class 'OSError'>, 'EnvironmentError': <class 'OSError'>, 'IOError': <class 'OSError'>, 'WindowsError': <class 'OSError'>, 'EOFError': <class 'EOFError'>, 'RuntimeError': <class 'RuntimeError'>, 'RecursionError': <class 'RecursionError'>, 'NotImplementedError': <class 'NotImplementedError'>, 'NameError': <class 'NameError'>, 'UnboundLocalError': <class 'UnboundLocalError'>, 'AttributeError': <class 'AttributeError'>, 'SyntaxError': <class 'SyntaxError'>, 'IndentationError': <class 'IndentationError'>, 'TabError': <class 'TabError'>, 'LookupError': <class 'LookupError'>, 'IndexError': <class 'IndexError'>, 'KeyError': <class 'KeyError'>, 'ValueError': <class 'ValueError'>, 'UnicodeError': <class 'UnicodeError'>, 'UnicodeEncodeError': <class 'UnicodeEncodeError'>, 'UnicodeDecodeError': <class 'UnicodeDecodeError'>, 'UnicodeTranslateError': <class 'UnicodeTranslateError'>, 'AssertionError': <class 'AssertionError'>, 'ArithmeticError': <class 'ArithmeticError'>, 'FloatingPointError': <class 'FloatingPointError'>, 'OverflowError': <class 'OverflowError'>, 'ZeroDivisionError': <class 'ZeroDivisionError'>, 'SystemError': <class 'SystemError'>, 'ReferenceError': <class 'ReferenceError'>, 'MemoryError': <class 'MemoryError'>, 'BufferError': <class 'BufferError'>, 'Warning': <class 'Warning'>, 'UserWarning': <class 'UserWarning'>, 'DeprecationWarning': <class 'DeprecationWarning'>, 'PendingDeprecationWarning': <class 'PendingDeprecationWarning'>, 'SyntaxWarning': <class 'SyntaxWarning'>, 'RuntimeWarning': <class 'RuntimeWarning'>, 'FutureWarning': <class 'FutureWarning'>, 'ImportWarning': <class 'ImportWarning'>, 'UnicodeWarning': <class 'UnicodeWarning'>, 'BytesWarning': <class 'BytesWarning'>, 'ResourceWarning': <class 'ResourceWarning'>, 'ConnectionError': <class 'ConnectionError'>, 'BlockingIOError': <class 'BlockingIOError'>, 'BrokenPipeError': <class 'BrokenPipeError'>, 'ChildProcessError': <class 'ChildProcessError'>, 'ConnectionAbortedError': <class 'ConnectionAbortedError'>, 'ConnectionRefusedError': <class 'ConnectionRefusedError'>, 'ConnectionResetError': <class 'ConnectionResetError'>, 'FileExistsError': <class 'FileExistsError'>, 'FileNotFoundError': <class 'FileNotFoundError'>, 'IsADirectoryError': <class 'IsADirectoryError'>, 'NotADirectoryError': <class 'NotADirectoryError'>, 'InterruptedError': <class 'InterruptedError'>, 'PermissionError': <class 'PermissionError'>, 'ProcessLookupError': <class 'ProcessLookupError'>, 'TimeoutError': <class 'TimeoutError'>, 'open': <built-in function open>, 'quit': Use quit() or Ctrl-Z plus Return to exit, 'exit': Use exit() or Ctrl-Z plus Return to exit, 'copyright': Copyright (c) 2001-2019 Python Software Foundation.
All Rights Reserved.

Copyright (c) 2000 BeOpen.com.
All Rights Reserved.

Copyright (c) 1995-2001 Corporation for National Research Initiatives.
All Rights Reserved.

Copyright (c) 1991-1995 Stichting Mathematisch Centrum, Amsterdam.
All Rights Reserved., 'credits':     Thanks to CWI, CNRI, BeOpen.com, Zope Corporation and a cast of thousands
    for supporting Python development.  See www.python.org for more information., 'license': Type license() to see the full license text, 'help': Type help() for interactive help, or help(object) for help about object.}, '__warningregistry__': {'version': 6}}, 0.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\dev\AREPL-vscode\node_modules\arepl-backend\python\arepl_python_evaluator.py", line 249, in main
    return_info = exec_input(execArgs)
  File "c:\dev\AREPL-vscode\node_modules\arepl-backend\python\arepl_python_evaluator.py", line 181, in exec_input
    sys.stdout.flush()
OSError: [Errno 9] Bad file descriptor

Print Output:
hi
```

Second run same thing but with `OSError: [WinError 6] The handle is invalid` instead

**Comment by Almenon** [comment]
I can't reproduce this in the shell with exec :(

```
>>> code="print('hi', file=open(1,'w'))"
>>> locals = {}
>>> exec(code,locals)
hi
>>> exec(code,locals)
hi              
```
