### ISSUE TITLE
asyncio.exceptions.CancelledError with simple async code

### ISSUE THREAD

**Issue by Almenon** [Almenon/AREPL-backend#167]
The simplified version of the hello world example from https://docs.python.org/3/library/asyncio.html:

```python
import asyncio


async def main():
    pass

asyncio.run(main())
```

results in a error being logged to stderr: 
```
Error on reading from the event loop self pipe
loop: <ProactorEventLoop running=True closed=False debug=False>
Traceback (most recent call last):
  File "C:\Users\almenon\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 768, in _loop_self_reading
    f.result()  # may raise
asyncio.exceptions.CancelledError
Error on reading from the event loop self pipe
loop: <ProactorEventLoop running=True closed=False debug=False>
Traceback (most recent call last):
  File "C:\Users\almenon\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 768, in _loop_self_reading
    f.result()  # may raise
asyncio.exceptions.CancelledError
```
(Note that it logs to stderr instead of throwing an exception because that's the default behavior of event loops - see `default_exception_handler` of `C:\Users\almenon\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py`.)

**Exepcted results:**
No error logged, same as when program is run via python directly

**Actual Results:**
Error logged.

OS: Windows 10
Python: v3.9

Full error: (logged if you specify `debug=True`)
<summary><details>
```
Error on reading from the event loop self pipe
handle_traceback: Handle created at (most recent call last):
  File "c:\Users\almenon\.vscode\extensions\almenon.arepl-2.0.2\node_modules\arepl-backend\python\arepl_python_evaluator.py", line 330, in <module>
    main(input())
  File "c:\Users\almenon\.vscode\extensions\almenon.arepl-2.0.2\node_modules\arepl-backend\python\arepl_python_evaluator.py", line 298, in main
    return_info = exec_input(execArgs)
  File "c:\Users\almenon\.vscode\extensions\almenon.arepl-2.0.2\node_modules\arepl-backend\python\arepl_python_evaluator.py", line 242, in exec_input
    run_context.run(exec, exec_args.evalCode, eval_locals)
  File "<string>", line 7, in <module>
  File "C:\Users\almenon\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\almenon\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\almenon\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 320, in run_forever
    self._self_reading_future.cancel()
  File "C:\Users\almenon\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 80, in cancel
    return super().cancel(msg=msg)
loop: <ProactorEventLoop running=True closed=False debug=True>
Traceback (most recent call last):
  File "C:\Users\almenon\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 768, in _loop_self_reading
    f.result()  # may raise
asyncio.exceptions.CancelledError
Error on reading from the event loop self pipe
handle_traceback: Handle created at (most recent call last):
  File "c:\Users\almenon\.vscode\extensions\almenon.arepl-2.0.2\node_modules\arepl-backend\python\arepl_python_evaluator.py", line 330, in <module>
    main(input())
  File "c:\Users\almenon\.vscode\extensions\almenon.arepl-2.0.2\node_modules\arepl-backend\python\arepl_python_evaluator.py", line 298, in main
    return_info = exec_input(execArgs)
  File "c:\Users\almenon\.vscode\extensions\almenon.arepl-2.0.2\node_modules\arepl-backend\python\arepl_python_evaluator.py", line 242, in exec_input
    run_context.run(exec, exec_args.evalCode, eval_locals)
  File "<string>", line 7, in <module>
  File "C:\Users\almenon\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 48, in run
    loop.run_until_complete(loop.shutdown_asyncgens())
  File "C:\Users\almenon\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\almenon\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 320, in run_forever
    self._self_reading_future.cancel()
  File "C:\Users\almenon\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 80, in cancel
    return super().cancel(msg=msg)
loop: <ProactorEventLoop running=True closed=False debug=True>
Traceback (most recent call last):
  File "C:\Users\almenon\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 768, in _loop_self_reading
    f.result()  # may raise
asyncio.exceptions.CancelledError
```
</details></summary>

**Comment by Almenon** [comment]
So basically the event loop is getting cancelled for some reason... but I'm not sure why. 

I tried doing a simple exec but that didn't get the error. I should try running arepl directly, mocking the JSON input, and changing code around untill I figure out what causes it.

**Comment by Almenon** [comment]
Note that this issue currently has the most votes (+3) to look into

**Comment by Almenon** [comment]
Can no longer reproduce, probably fixed by https://github.com/Almenon/AREPL-backend/pull/193
