### ISSUE TITLE
asyncio error on mac

### ISSUE THREAD

**Issue by Almenon** [Almenon/AREPL-backend#174]
https://github.com/Almenon/AREPL-vscode/issues/387

Reproduction Requirements:
* MacOS Mojave or higher - ex 11.2.3 (Big Sur)
* python v3.9

The bug can be reproduced with a simple import statement: `import math`

BrandonNav says that changing the following https://github.com/Almenon/AREPL-backend/blob/dfe6b61de2ce87c9f3a717c0e92c5463e8fe391b/python/arepl_python_evaluator.py#L234 to `asyncio.set_event_loop(asyncio.get_event_loop())` fixes it.

**Comment by Almenon** [comment]
set_event_loop(*loop*): Set *loop* as a current event loop for the current OS thread.

The documentation for new_event_loop (current code) simply says `Create a new event loop object.`

The documentation for get_event_loop (proposed change) says:
```
Get the current event loop.

If there is no current event loop set in the current OS thread, the OS thread is main, and set_event_loop() has not yet been called, asyncio will create a new event loop and set it as the current one.

Because this function has rather complex behavior (especially when custom event loop policies are in use), using the get_running_loop() function is preferred to get_event_loop() in coroutines and callbacks.

Consider also using the asyncio.run() function instead of using lower level functions to manually create and close an event loop.
```

The problem here is that `asyncio.set_event_loop(asyncio.get_event_loop())` is a no-op most of the time. Why set loop to the current event loop if it's already the current event loop? To avoid side-effects between runs I need a fresh loop.

**Comment by Almenon** [comment]
Also some notes on the exception thrown:
```

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 261, in _add_reader
    key = self._selector.get_key(fd)
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/selectors.py", line 193, in get_key
    raise KeyError("{!r} is not registered".format(fileobj)) from None
KeyError: '5 is not registered'
```

Called upon the creation of the event loop, not exactly sure what it's trying to do but regardless it tries a different method _selector.register in the exception handler.

```
Traceback (most recent call last):
  File "/Users/jb/.vscode/extensions/almenon.arepl-2.0.2/node_modules/arepl-backend/python/arepl_python_evaluator.py", line 298, in main
    return_info = exec_input(execArgs)
  File "/Users/jb/.vscode/extensions/almenon.arepl-2.0.2/node_modules/arepl-backend/python/arepl_python_evaluator.py", line 234, in exec_input
    asyncio.set_event_loop(asyncio.new_event_loop())
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 761, in new_event_loop
    return get_event_loop_policy().new_event_loop()
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 659, in new_event_loop
    return self._loop_factory()
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/unix_events.py", line 54, in __init__
    super().__init__(selector)
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 61, in __init__
    self._make_self_pipe()
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 112, in _make_self_pipe
    self._add_reader(self._ssock.fileno(), self._read_from_self)
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 263, in _add_reader
    self._selector.register(fd, selectors.EVENT_READ,
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/selectors.py", line 523, in register
    self._selector.control([kev], 0, 0)
TypeError: changelist must be an iterable of select.kevent objects
```

This is the main error. The last line is a method of KqueueSelector, which is specific to BSD OS's like mac. `kev` is from the line above:
```
kev = select.kevent(key.fd, select.KQ_FILTER_READ,
                                        select.KQ_EV_ADD)
```
I'm guessing the kevent was not found and kev is null. Really wish I had a mac to investigate this.

```
Print Output:
Exception ignored in: <function BaseEventLoop.__del__ at 0x11871de50>
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 683, in __del__
    self.close()
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/unix_events.py", line 60, in close
    for sig in list(self._signal_handlers):
AttributeError: '_UnixSelectorEventLoop' object has no attribute '_signal_handlers'
```

Not sure what's going on here.

**Comment by Almenon** [comment]
Relevant docs:
https://docs.python.org/3/library/asyncio-eventloop.html#event-loop-methods
https://docs.python.org/3/library/select.html#kevent-objects
https://www.freebsd.org/cgi/man.cgi?query=kqueue&sektion=2

**Comment by Almenon** [comment]
Might be worth reporting this as a python bug

**Comment by Almenon** [comment]
should be fixed by https://github.com/Almenon/AREPL-backend/pull/193
