### ISSUE TITLE
closing async loop affects next AREPL run

### ISSUE THREAD

**Issue by Almenon** [Almenon/AREPL-backend#30]
The context should be totally erased with each AREPL run and begun anew.  However running an async program will somehow affect the next run if you close the event loop. To fix this I need to reset the event loop beforehand.

```python
asyncio.set_event_loop(asyncio.new_event_loop()) 
```

Example program:

```python
import asyncio
import time
import random

# asyncio.set_event_loop(asyncio.new_event_loop()) 
# without above fix the second run will fail

# run the_sync_run()
async def async_run(name):
    random_int = random.randint(50000, 54304231)
    start_time = time.time()
    for i in range(0, random_int): # webpage
        pass
    ellapsed_time = time.time() - start_time
    msg = "elapsed time: " + str(ellapsed_time) 
    print(msg)
    return msg

def compile_async_tasks():
    tasks = []

    for i in range(0,4):
        name = "Async Iteration " + str(i)
        tasks.append(
            asyncio.ensure_future(async_run(name))
        )
    print(tasks)
    return tasks

tasks = compile_async_tasks()

start_time = time.time()
loop = asyncio.get_event_loop()
loop.run_until_complete(asyncio.gather(*tasks))
loop.close()

ellapsed_time = time.time() - start_time
print("Async looop took " + str(ellapsed_time))
```

Error:
> Traceback (most recent call last):
  line 29, in <module>
  line 24, in compile_async_tasks
  File "C:\Program Files\Python36\lib\asyncio\tasks.py", line 512, in ensure_future
    task = loop.create_task(coro_or_future)
  File "C:\Program Files\Python36\lib\asyncio\base_events.py", line 282, in create_task
    self._check_closed()
  File "C:\Program Files\Python36\lib\asyncio\base_events.py", line 357, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

Thanks to @HQupgradeHQ for the example program.  I found the issue out while investigating https://github.com/Almenon/AREPL-vscode/issues/60

**Comment by Almenon** [comment]
This code resulted in https://github.com/Almenon/AREPL-vscode/issues/387. I'll have to try to make a solution that fixes both issues.
