### ISSUE TITLE
p5 causes jsonPickle to fail

### ISSUE THREAD

**Issue by Almenon** [Almenon/AREPL-backend#32]
```python
from p5 import *

def setup():
    size(640, 360)
    no_stroke()
    background(204)

def draw():
    if mouse_is_pressed:
        fill(random_uniform(255), random_uniform(127), random_uniform(51), 127)
    else:
        fill(255, 15)

    circle_size = random_uniform(low=10, high=80)

    circle((mouse_x, mouse_y), circle_size)

def key_pressed(event):
    background(204)

run()
```

Result:

> Sorry, AREPL has ran into an error

> Traceback (most recent call last):
  File "C:\Users\almenon\.vscode\extensions\almenon.arepl-0.0.9\node_modules\arepl-backend\python\pythonEvaluator.py", line 205, in <module>
    returnInfo = exec_input(data.evalCode, data.savedCode)
  File "C:\Users\almenon\.vscode\extensions\almenon.arepl-0.0.9\node_modules\arepl-backend\python\pythonEvaluator.py", line 183, in exec_input
    userVariables = pickle_user_vars(evalLocals)
  File "C:\Users\almenon\.vscode\extensions\almenon.arepl-0.0.9\node_modules\arepl-backend\python\pythonEvaluator.py", line 138, in pickle_user_vars
    return jsonpickle.encode(userVariables, max_depth=100) # any depth above 245 resuls in error and anything above 100 takes too long to process
  File "C:\Users\almenon\.vscode\extensions\almenon.arepl-0.0.9\node_modules\arepl-backend\python\jsonpickle\_\_init\_\_.py", line 132, in encode
    numeric_keys=numeric_keys)
  File "C:\Users\almenon\.vscode\extensions\almenon.arepl-0.0.9\node_modules\arepl-backend\python\jsonpickle\pickler.py", line 43, in encode
    return backend.encode(context.flatten(value, reset=reset))
  File "C:\Users\almenon\.vscode\extensions\almenon.arepl-0.0.9\node_modules\arepl-backend\python\jsonpickle\pickler.py", line 156, in flatten
    return self._flatten(obj)
  File "C:\Users\almenon\.vscode\extensions\almenon.arepl-0.0.9\node_modules\arepl-backend\python\jsonpickle\pickler.py", line 160, in _flatten
    return self._pop(self._flatten_obj(obj))
  File "C:\Users\almenon\.vscode\extensions\almenon.arepl-0.0.9\node_modules\arepl-backend\python\jsonpickle\pickler.py", line 176, in _flatten_obj
    return flatten_func(obj)
  File "C:\Users\almenon\.vscode\extensions\almenon.arepl-0.0.9\node_modules\arepl-backend\python\jsonpickle\pickler.py", line 433, in _flatten_dict_obj
    flatten(k, v, data)
  File "C:\Users\almenon\.vscode\extensions\almenon.arepl-0.0.9\node_modules\arepl-backend\python\jsonpickle\pickler.py", line 508, in _flatten_key_value_pair
    data[k] = self._flatten(v)
  File "C:\Users\almenon\.vscode\extensions\almenon.arepl-0.0.9\node_modules\arepl-backend\python\jsonpickle\pickler.py", line 160, in _flatten
    return self._pop(self._flatten_obj(obj))
  File "C:\Users\almenon\.vscode\extensions\almenon.arepl-0.0.9\node_modules\arepl-backend\python\jsonpickle\pickler.py", line 176, in _flatten_obj
    return flatten_func(obj)
  File "C:\Users\almenon\.vscode\extensions\almenon.arepl-0.0.9\node_modules\arepl-backend\python\jsonpickle\pickler.py", line 234, in _ref_obj_instance
    return self._flatten_obj_instance(obj)
  File "C:\Users\almenon\.vscode\extensions\almenon.arepl-0.0.9\node_modules\arepl-backend\python\jsonpickle\pickler.py", line 404, in _flatten_obj_instance
    return self._flatten_dict_obj(obj.\_\_dict\_\_, data)
  File "C:\Users\almenon\.vscode\extensions\almenon.arepl-0.0.9\node_modules\arepl-backend\python\jsonpickle\pickler.py", line 433, in _flatten_dict_obj
    flatten(k, v, data)
  File "C:\Users\almenon\.vscode\extensions\almenon.arepl-0.0.9\node_modules\arepl-backend\python\jsonpickle\pickler.py", line 508, in _flatten_key_value_pair
    data[k] = self._flatten(v)
  File "C:\Users\almenon\.vscode\extensions\almenon.arepl-0.0.9\node_modules\arepl-backend\python\jsonpickle\pickler.py", line 160, in _flatten
    return self._pop(self._flatten_obj(obj))
  File "C:\Users\almenon\.vscode\extensions\almenon.arepl-0.0.9\node_modules\arepl-backend\python\jsonpickle\pickler.py", line 176, in _flatten_obj
    return flatten_func(obj)
  File "C:\Users\almenon\.vscode\extensions\almenon.arepl-0.0.9\node_modules\arepl-backend\python\jsonpickle\pickler.py", line 234, in _ref_obj_instance
    return self._flatten_obj_instance(obj)
  File "C:\Users\almenon\.vscode\extensions\almenon.arepl-0.0.9\node_modules\arepl-backend\python\jsonpickle\pickler.py", line 404, in _flatten_obj_instance
    return self._flatten_dict_obj(obj\._\_dict\_\_, data)
  File "C:\Users\almenon\.vscode\extensions\almenon.arepl-0.0.9\node_modules\arepl-backend\python\jsonpickle\pickler.py", line 433, in _flatten_dict_obj
    flatten(k, v, data)
  File "C:\Users\almenon\.vscode\extensions\almenon.arepl-0.0.9\node_modules\arepl-backend\python\jsonpickle\pickler.py", line 508, in _flatten_key_value_pair
    data[k] = self.\_flatten(v)
  File "C:\Users\almenon\.vscode\extensions\almenon.arepl-0.0.9\node_modules\arepl-backend\python\jsonpickle\pickler.py", line 160, in _flatten
    return self._pop(self._flatten_obj(obj))
  File "C:\Users\almenon\.vscode\extensions\almenon.arepl-0.0.9\node_modules\arepl-backend\python\jsonpickle\pickler.py", line 176, in _flatten_obj
    return flatten_func(obj)
  File "C:\Users\almenon\.vscode\extensions\almenon.arepl-0.0.9\node_modules\arepl-backend\python\jsonpickle\pickler.py", line 234, in _ref_obj_instance
    return self._flatten_obj_instance(obj)
  File "C:\Users\almenon\.vscode\extensions\almenon.arepl-0.0.9\node_modules\arepl-backend\python\jsonpickle\pickler.py", line 290, in _flatten_obj_instance
    reduce_val = obj.\_\_reduce\_\_()
ValueError: ctypes objects containing pointers cannot be pickled

**Comment by Almenon** [comment]
Rather than creating a customhandler for every fail case i get I should focus my efforts on #33 (making jsonPickle fail-safe).  Then I can look into pickling wierd cases like this one.

**Comment by Almenon** [comment]
canvas.hdc is the specific var that caused the issue
